require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

inherit_from:
  - ./.rubocop.rspec.yml
  - ./.rubocop.rails.yml


AllCops:
  CacheRootDirectory: tmp
  DisabledByDefault: true
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.1
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Lint/Void:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/UselessAssignment:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Security:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/BlockAlignment:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/CommentIndentation:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/DotPosition:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyComment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundArguments:
  Enabled: true

Layout/EmptyLinesAroundBeginBody:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Layout/EndOfLine:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/AssignmentIndentation:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

# TODO: feedback needed
Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/RescueEnsureAlignment:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: false

Lint/BigDecimalNew:
  Enabled: true

Lint/BooleanSymbol:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/Debugger:
  Enabled: true
  DebuggerMethods:
    BP:
      bp

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EmptyWhen:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/IneffectiveAccessModifier:
  Enabled: true

# https://ruby-doc.org/core-2.2.0/Exception.html
Lint/InheritException:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/MultipleComparison:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/NestedPercentLiteral:
  Enabled: true

Lint/NextWithoutAccumulator:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/PercentStringArray:
  Enabled: true

Lint/PercentSymbolArray:
  Enabled: true

Lint/RandOne:
  Enabled: true

Lint/RedundantWithIndex:
  Enabled: true

Lint/RedundantWithObject:
  Enabled: true

Lint/RegexpAsCondition:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

# https://github.com/bbatsov/ruby-style-guide#no-blind-rescues
Lint/RescueException:
  Enabled: true

Lint/RescueType:
  Enabled: true

Lint/ReturnInVoidContext:
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true

Lint/SafeNavigationConsistency:
  Enabled: true

Lint/ScriptPermission:
  Enabled: true

Lint/ShadowedArgument:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Lint/Syntax:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnifiedInteger:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantCopEnableDirective:
  Enabled: true

Lint/RedundantRequireStatement:
  Enabled: true

Lint/RedundantSplatExpansion:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/UselessElseWithoutRescue:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Metrics/BlockNesting:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true

Naming/AsciiIdentifiers:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/HeredocDelimiterCase:
  Enabled: true

Naming/HeredocDelimiterNaming:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Style/Alias:
  Enabled: true

#  https://github.com/bbatsov/ruby-style-guide#no-and-or-or
Style/AndOr:
  Enabled: true

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/Attr:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassMethods:
  Enabled: true

# https://github.com/bbatsov/ruby-style-guide#no-class-vars
Style/ClassVars:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/ColonMethodDefinition:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/DateTime:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/Dir:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EmptyBlockParameter:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EndBlock:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/For:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/IfUnlessModifierOfIfUnless:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MixinUsage:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedModifier:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/Not:
  Enabled: true

Style/OrAssignment:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/RandomWithOffset:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TrailingBodyOnClass:
  Enabled: true

Style/TrailingBodyOnMethodDefinition:
  Enabled: true

Style/TrailingBodyOnModule:
  Enabled: true

Style/TrailingMethodEndStatement:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 200

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent

Layout/SpaceBeforeComma:
  Enabled: true

Security/IoMethods:
  Enabled: true

Security/CompoundHash:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/RedundantAssignment:
  Enabled: true

Style/RedundantCondition:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true
  ForceEqualSignAlignment: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/OpenStructUse: # new in 1.23
  Enabled: true
  Exclude:
    - "spec/**/*"

Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true

Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true

Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true

Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true

Lint/AmbiguousRange: # new in 1.19
  Enabled: true

Lint/DeprecatedConstants: # new in 1.8
  Enabled: true
  Include:
    - '**/v6/**.rb'
  DeprecatedConstants:
    FactoryGirl:
      Alternative: FactoryBot

Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true

Lint/EmptyClass: # new in 1.3
  Enabled: true

Lint/EmptyInPattern: # new in 1.16
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true

Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true

Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true

Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true

Lint/RefinementImportMethods: # new in 1.27
  Enabled: true

Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true

Lint/SymbolConversion: # new in 1.9
  Enabled: true

Lint/ToEnumArguments: # new in 1.1
  Enabled: true

Lint/TripleQuotes: # new in 1.9
  Enabled: true

Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true

Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true

Naming/BlockForwarding: # new in 1.24
  Enabled: true

Style/ArgumentsForwarding: # new in 1.1
  Enabled: true

Style/CollectionCompact: # new in 1.2
  Enabled: true

Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: true

Style/EndlessMethod: # new in 1.8
  Enabled: true

Style/FetchEnvVar: # new in 1.28
  Enabled: true

Style/FileRead: # new in 1.24
  Enabled: true

Style/FileWrite: # new in 1.24
  Enabled: true

Style/HashConversion: # new in 1.10
  Enabled: true

Style/HashExcept: # new in 1.7
  Enabled: true

Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: true

Style/InPatternThen: # new in 1.16
  Enabled: true

Style/MapToHash: # new in 1.24
  Enabled: true

Style/MultilineInPatternThen: # new in 1.16
  Enabled: true

Style/NegatedIfElseCondition: # new in 1.2
  Enabled: true

Style/NestedFileDirname: # new in 1.26
  Enabled: true

Style/NilLambda: # new in 1.3
  Enabled: true

Style/NumberedParameters: # new in 1.22
  Enabled: true

Style/NumberedParametersLimit: # new in 1.22
  Enabled: true

Style/QuotedSymbols: # new in 1.16
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes


Style/RedundantInitialize: # new in 1.27
  Enabled: true

Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true

Style/StringChars: # new in 1.12
  Enabled: true

Style/SwapValues: # new in 1.1
  Enabled: true

Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true

Style/SelectByRegexp: # new in 1.22
  Enabled: true
  Exclude:
    - Dangerfile

Lint/DuplicateBranch: # new in 1.3
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true

Style/RedundantArgument: # new in 1.4
  Enabled: true
