Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/SaveBang:
  Enabled: false
  Exclude:
    - 'spec/**/*'

Rails/ScopeArgs:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Rails/UniqBeforePluck:
  Enabled: true

Rails/UnknownEnv:
  Enabled: true
  Environments: ['production', 'test', 'development', 'staging']

Rails/Validation:
  Enabled: true

Rails/ActionFilter:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true

Rails/EnvironmentComparison:
  Enabled: true

Rails/Exit:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/ActionControllerTestCase:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AddColumnIndex:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/AttributeDefaultBlockValue:
  Enabled: true

Rails/CompactBlank:
  Enabled: true

Rails/DuplicateAssociation:
  Enabled: true

Rails/DuplicateScope:
  Enabled: true

Rails/DurationArithmetic:
  Enabled: true

Rails/EagerEvaluationLogMessage:
  Enabled: true

Rails/ExpandedDateRange:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/I18nLazyLookup:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/MigrationClassName:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RedundantTravelBack:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/RootJoinChain:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/TimeZoneAssignment:
  Enabled: true

Rails/TransactionExitStatement:
  Enabled: true

Rails/UnusedIgnoredColumns:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/NegateInclude:
  Enabled: true
  Exclude:
    - Dangerfile

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true

Rails/I18nLocaleAssignment:
  Enabled: true
