version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '8432:5432'
    volumes:
      - chic-app-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '9379:6379'
    volumes:
      - chic-app-redis:/var/lib/redis/data
volumes:
  chic-app-postgres:
  chic-app-redis:
