default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  port: 8432
  database: gateway_chic_development
  username: dev-user
  password: 123456

test:
  <<: *default
  host: localhost
  port: 8432
  database: gateway_chic_test
  username: dev-user
  password: 123456

production:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
